import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/shared/Navbar";
import WorkoutProvider from "./Components/Context/WorkoutContext";
import Footer from "./Components/shared/HomePage/Footer";
const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" 
        data-theme='light'
      className={`${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <WorkoutProvider>
          <Navbar />
          {children}
          <Footer />
        </WorkoutProvider>
        </body>
    </html>
  );
}
